sudo: required

language: go

go:
- "1.12"

matrix:
  include:
    - name: "Postgres 9.6"
      dist: trusty
      env:
        - PGDB=9.6 RELEASE=true PGIS=2.4
    - name: "Postgres 10"
      dist: trusty
      env:
        - PGDB=10 PGIS=2.4
    - name: "Postgres 11"
      dist: bionic
      env:
        - PGDB=11 PGIS=2.5
env:
  global:
    - GO111MODULE=on

before_install:
  # setup postgresql
  - sudo -E service postgresql stop 9.2
  - sudo -E service postgresql stop 9.3
  - sudo -E service postgresql stop 9.4
  - sudo -E service postgresql stop 9.5
  - sudo -E service postgresql stop 9.6
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install postgresql-$PGDB postgresql-client-$PGDB postgresql-$PGDB-postgis-$PGIS postgresql-$PGDB-postgis-$PGIS-scripts
  - sudo -E sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo -E sed -i 's/port = 5433/port = 5432/' /etc/postgresql/*/main/postgresql.conf
  - sudo -E service postgresql restart $PGDB
  
before_script:
  - psql -U postgres -c "CREATE USER travis;" || true
  - psql -U postgres -c "ALTER ROLE travis WITH SUPERUSER;" || true
  - psql -U postgres -c "CREATE DATABASE archiver_test;"

script:
- go test -p=1 -coverprofile=coverage.text -covermode=atomic github.com/nyaruka/rp-archiver/...

after_success:
- bash <(curl -s https://codecov.io/bash)
- rm coverage.text

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $RELEASE = true
